namespace:
  name: sandbox
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
deploy:
  replicaCount: 1
image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests: 
      mem: 64Mi
      cpu: 250m
    limits: 
      mem: 128Mi
      cpu: 500m
  containerPort: 3111
  livenessProbe:
    path: /healthz
    port: 3111
  readinessProbe:
    path: /healthz
    port: 3111