name: Run Pytest
on: [push]

jobs:
  run_pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Requirements
        working-directory: ./project/techtrends
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run Pytest
        working-directory: ./project/techtrends
        run: |
          python init_db.py
          pytest app.py
